### PR TITLE
Client installer

### PR DESCRIPTION
**Pull request by mbasti-rh**
First part, I just moved code to module, more improvements later

### CODE REVIEW

**Comment by stlaz** [comment]
I would personally prefer having the configure files created in a way as in my commit https://github.com/stlaz/freeipa/commit/50913d509c4db646cc13115ebeb2dc878dec0922 as it is far too better readable. But as we need this pushed soon, I will just check if this does not break anything and I can do that configure readability later.

**Comment by stlaz** [comment]
ACK, this works. Feel free to include my mentioned patch (check if it works first, might have left some mistakes in).

**Comment by stlaz** [comment]
This breaks Kerberos configuration:
/etc/krb5.conf part that's broken:

```
...

domain_realm = [{'type': 'option', 'name': '.dom-197.abc.idm.lab.eng.brq.redhat.com', 'value': 'DOM-197.ABC.IDM.LAB.ENG.BRQ.REDHAT.COM'}, {'type': 'option', 'name': 'dom-197.abc.idm.lab.eng.brq.redhat.com', 'value': 'DOM-197.ABC.IDM.LAB.ENG.BRQ.REDHAT.COM'}, {'type': 'option', 'name': 'vm-090.abc.idm.lab.eng.brq.redhat.com', 'value': 'DOM-197.ABC.IDM.LAB.ENG.BRQ.REDHAT.COM'}, {'action': 'set', 'type': 'option', 'name': '.abc.idm.lab.eng.brq.redhat.com', 'value': 'DOM-197.ABC.IDM.LAB.ENG.BRQ.REDHAT.COM'}, {'action': 'set', 'type': 'option', 'name': 'abc.idm.lab.eng.brq.redhat.com', 'value': 'DOM-197.ABC.IDM.LAB.ENG.BRQ.REDHAT.COM'}]
```

**Comment by stlaz** [comment]
ACK, if you want you can try it out with my krb5 config patch and if it works push it with it (I updated it so it should work OK as well).

**Comment by stlaz** [comment]
Works as expected, ACK.

**Comment by jcholast** [comment]
Added ticket number and pushed to installer-refactoring: 4df86213b7431715522bc02f1b41708876f21eda.

**Pull request closed without merging**
